#!/usr/bin/env node
'use strict'

const program = require('commander');

program
  .usage('<component_name>')
  .version(require(`${__dirname}/package.json`).version, '-v, --version')
  .parse(process.argv);

Promise.resolve()
  .then(() => console.log('create-component-container'))
  .catch(err => {
    console.log('Fail!');
    console.error(err)
  });
