#!/usr/bin/env node
'use strict'

const program = require('commander');
const fs = require('fs-extra');

program
  .usage('<component_name>')
  .version(require(`${__dirname}/package.json`).version, '-v, --version')
  .parse(process.argv);

const getSrcDir = dir => {
  let srcDir = `${dir}/src`;

  dir.split('/').forEach((dirItem, index) => {
    if(dirItem === 'src')
      srcDir = dir.split('/').slice(0, index).join('/') + '/src';
  });

  return srcDir;
};

const srcDir = getSrcDir(process.cwd());
console.log(srcDir);

Promise.resolve()
  .then(() => fs.readFile(`${__dirname}/minimum/minimumComponent.tsx`, 'utf8'))
  .then(data => fs.outputFile(`${srcDir}/components/XXXComponent.tsx`, data))
  .then(() => fs.readFile(`${__dirname}/minimum/minimumContainer.ts`, 'utf8'))
  .then(data => fs.outputFile(`${srcDir}/containers/XXXContainer.ts`, data))
  .catch(err => {
    console.log('Fail!');
    console.error(err)
  });
